# Generated by Django 4.1.1 on 2022-12-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorgrequest',
            name='cat',
            field=models.CharField(choices=[(0, 'Лекция'), (1, 'Мастер-класс'), (2, 'Хакатон')], max_length=10, verbose_name='Категории'),
        ),
    ]
