# Generated by Django 4.1.1 on 2022-12-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_eventorgrequest_cat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventorgrequest',
            name='cat',
        ),
        migrations.AddField(
            model_name='eventorgrequest',
            name='category',
            field=models.IntegerField(choices=[(0, 'Лекция'), (1, 'Мастер-класс'), (2, 'Хакатон')], default=0, verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='eventorgrequest',
            name='date_time',
            field=models.DateTimeField(blank=True, verbose_name='Время проведения мероприятия'),
        ),
        migrations.AlterField(
            model_name='eventorgrequest',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Рассмотрено'),
        ),
    ]
