# Generated by Django 4.1.1 on 2022-12-21 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0006_alter_eventorgrequest_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coworking',
            options={'ordering': ['id'], 'verbose_name': 'Интервал', 'verbose_name_plural': 'Интервалы'},
        ),
        migrations.RemoveField(
            model_name='coworking',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='coworking',
            name='time_create',
        ),
        migrations.RemoveField(
            model_name='coworking',
            name='username',
        ),
        migrations.AddField(
            model_name='coworking',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата, на которую бронируется коворкинг'),
        ),
        migrations.AddField(
            model_name='coworking',
            name='time',
            field=models.TimeField(null=True, verbose_name='Время, на которое бронируется коворкинг'),
        ),
        migrations.AddField(
            model_name='coworking',
            name='unique_num',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='coworking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Бронирующий'),
        ),
    ]
