# Generated by Django 4.1.1 on 2022-11-29 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import event.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='EventList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_num', models.IntegerField(default=event.models.get_unique_num, unique=True, verbose_name='Код')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='event.event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
            options={
                'verbose_name': 'Запись на мероприятие',
                'verbose_name_plural': 'Записи на мероприятия',
                'ordering': ['id'],
            },
        ),
    ]
