# Generated by Django 4.1.1 on 2022-11-29 16:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_alter_event_photo_eventlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlist',
            name='unique_num',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
