# Generated by Django 4.1.1 on 2022-12-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_eventlist_unique_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, verbose_name='Описание мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название мероприятия'),
        ),
    ]
