# Generated by Django 4.1.1 on 2022-12-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_event_options_eventrequestlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cat',
            field=models.CharField(choices=[(0, 'Лекция'), (1, 'Мастер-класс'), (2, 'Хакатон')], max_length=10, verbose_name='Категории'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
